#!/usr/bin/env bash

# exit when a command fails
set -o errexit


TEXFILE=report3

rm -f *.aux *.log *.bbl *.blg *.dvi *.fdb_latexmk *.fls *.brf *.lof *.out *.toc

# latexmk ${TEXFILE}
pdflatex ${TEXFILE}
bibtex ${TEXFILE}
pdflatex ${TEXFILE}
pdflatex ${TEXFILE}


rm -f *.aux *.log *.bbl *.blg *.dvi *.fdb_latexmk *.fls *.brf *.lof *.out *.toc
